#General constants
LINE_WIDTH = 2

#Screen constants
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 790

#UI constants
SCOREBOARD_POS_X = 0
SCOREBOARD_POS_Y = 720
SCOREBOARD_WIDTH = 1280
SCOREBOARD_HEIGHT = 70
SCOREBOARD_TEXT_OFFSET = 20
SCOREBOARD_TEXT_SIZE = 30
SCOREBOARD_LIFE_CONTAINER_OFFSET = 24
SCOREBOARD_BOMB_CONTAINER_OFFSET = 39

#Asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#Player constants
PLAYER_SIZE = 20
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_TURN_SPEED = 300
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

#Shot constants
SHOT_RADIUS = 5

#Bomb constants
PLAYER_BOMB_COOLDOWN_SECONDS = 3
BOMB_RADIUS = 10
BOMB_EXPLOSION_RADIUS = 200

#Upgrades
MAX_LIVES = 5
MAX_BOMB_AMMO = 5
